# Generated by Django 4.2 on 2023-05-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0038_cart_item_alter_shoe_img_delete_user_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="img",
            field=models.ImageField(upload_to="static/Media"),
        ),
    ]
